### ISSUE TITLE
I can't this on Samsung Galaxy S4.

### ISSUE THREAD

**Issue by blitzerbit** [HaydnTrigg/JBox2D-Demo#1]
This can't use on Samsung Galaxy S4. Because Samsung Galaxy S4 don't provide OpenGL ES2.
pls help me asap.
Thank you.

**Comment by HaydnTrigg** [comment]
You should be able to build this project for the Samsung S4, I've been able to build it for both my Galaxy S and Galaxy S5. 

Can you provide some more information to help me understand how you set up the project? Are you able to build it for the PC emulator?

**Comment by blitzerbit** [comment]
Thanks for your reply.
game = new Game(this)

I can't see canvas screen. only Samsung Galaxy s4, Android Version : 5.0.1. I hope you check it through teamviewer.
I think it is good to use JDK library.
my mail address : angel8280@yandex.com, angel8280@mail.com
Waiting for your reply.
Pls help me asap. Thank you.
